version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.12.0
  - dependency-name: lxml
    versions:
    - 4.6.2
