- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: file-contents-sorter
    files: .gitignore
  - id: flake8
    args: ["--max-line-length=88"]
  - id: name-tests-test
    args: ["--django"]
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.711
  hooks:
  - id: mypy

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.7.0
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v1.4.1
    hooks:
    -   id: add-trailing-comma
