language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip
before_install:
- pip install poetry
- poetry install
- pip install reorder-python-imports
- pip install add-trailing-comma
script: pre-commit run --all-files
